### ISSUE TITLE
Clarify the meaning of uncertainty

### ISSUE THREAD

**Issue by minhhpham** [MobilityData/transit#18]
Currently, the precise meaning of `uncertainty` in [TripUpdate ](https://github.com/MobilityData/transit/blob/d0c743da958214d2b7a15971f5e1c2149967f11c/gtfs-realtime/spec/en/trip-updates.md) has not been defined. Different producers have different values where uncertainty has different meanings. This causes problems because consumers has to have different interpretation for different producers. 

We used the [gtfs-realtime-validator](https://github.com/CUTR-at-USF/gtfs-realtime-validator/tree/7962b371fd688f045c73a86970cbddd71eac0f85) tool to find the agencies that use `uncertainty` and what value of `uncertainty` they publish in their feeds. There are 6 agencies:

Feed | uncertainty value
-- | --
OCTA Trip Updates | 0
Thunder Bay Transit Trip Updates | 0
HART Trip Updates | 30
BART Trip Updates | 30
Kingston Transit Trip Updates | 0
MBTA Trip Updates | 300

Note that all of these agencies use the same values of `uncertainty` across their `stop_time_update` entities.

**Comment by barbeau** [comment]
Still valid

**Comment by emmambd** [comment]
Closing since this issue is already referenced in the relevant PR discussion in google/transit, which has since gone stale.
