### ISSUE TITLE
Should shape_point be repeated?

### ISSUE THREAD

**Issue by scrudden** [MobilityData/transit#48]
https://github.com/MobilityData/transit/blob/c3257ed51fd991b7b7c11b8d57f5422e2eef99e0/gtfs-realtime/proto/gtfs-realtime.proto#L910

**Comment by barbeau** [comment]
@scrudden Yes, good catch! I just added a comment to the pull request directly at https://github.com/MobilityData/transit/pull/47/files#r384112551, so I'll close this.
