### ISSUE TITLE
GTFS Flex and Fares v2

### ISSUE THREAD

**Issue by brodyFlannigan** [MobilityData/transit#60]
# [GTFS-Flex](https://docs.google.com/document/d/1QVrijt2omNN_lvCkC0FmRhciVmWg-cJtNW_PqULc-Pw/edit#heading=h.9i1fb17t3lbp) and [GTFS-Fares v2](https://docs.google.com/document/d/19j-f-wZ5C_kYXmkLBye1g42U-kvfSVgYLkkG5oyBauY/edit#heading=h.nwzbwwbq5faf)
We are currently looking at ways of modelling fares for flexible trips (as defined in GTFS-Flex) using GTFS-Fares v2.

Here are the three cases I have identified where particular fares may be applied with ideas on how they could be resolved:

### Situation
In some transit systems, an extra fee may be charged to a rider that has requested that a bus deviate (i.e. [flexible trips](https://docs.google.com/document/d/1QVrijt2omNN_lvCkC0FmRhciVmWg-cJtNW_PqULc-Pw/edit#bookmark=kix.nll7l9r3ccy6)) to accomodate their needs.
### Possible solutions
A new `location_group_id` field could be defined for [`fare_areas.txt`](https://docs.google.com/document/d/19j-f-wZ5C_kYXmkLBye1g42U-kvfSVgYLkkG5oyBauY/edit#bookmark=kix.20b918vmxq03). This field would be used in the same way as the `stop_id` field in `fare_areas.txt`. Using `fare_leg_rules.amount` (to provide a fixed fee for deviation) or `fare_leg_rules.min_amount` and `fare_leg_rules.max_amount` to describe a variable cost for a deviation service.
In a case where a flat fare is charged for a bracket of distances (e.g. if a deviation is between 1 and 10 km, the fare is 2$, but if it is more than 10 km, the fare is 15$), the `fare_leg_rules.amount` could be used.

### Situation
Some Demand-Response Transit (DRT) systems charge the rider depending on the distance they travelled.
### Possible solutions:
In combination with the `fare_areas.location_group_id` field, as well as the already-proposed `fare_leg_rules.min_fare_distance`, `fare_leg_rules.max_fare_distance` as well as  `fare_leg_rules.min_amount` and `fare_leg_rules.max_amount`, the minimum and maximum distances and amounts could be defined.

In a case where a flat fare is charged for a bracket of distances (e.g. if a trip is between 1 and 10 km, the fare is 2$, but if it is more than 10 km, the fare is 15$), the `fare_leg_rules.amount` could be used. See the [Transcollines Rural public transport](https://transcollines.ca/rural-public-transport/) fare chart for details

### Situation
Some DRT systems charge riders different fares depending on different "zones" that are predetermined.
## Possible solutions:
In combination with the `fare_areas.location_group_id` field, as well as the already-proposed `fare_leg_rules.from_area_id`, `fare_leg_rules.to_area_id` as well as  `fare_leg_rules.amount`, the amount for zone-to-zone travel could be established.

In a case like  [Transcollines Rural public transport](https://transcollines.ca/rural-public-transport/), where both distance and zones are factors in calculating the fare charged, `fare_leg_rules.to_area_id` and `fare_leg_rules.from_area_id` would be used to determine the fare zones being travelled through, then `fare_leg_rules.min_fare_distance` and `fare_leg_rules.max_fare_distance` would be used to determine the distance fare to be charged.

**Comment by e-lo** [comment]
I think this should be in https://github.com/google/transit ?
