### ISSUE TITLE
Clarify `route_sort_order` description

### ISSUE THREAD

**Issue by giocorti** [MobilityData/transit#9]
The route_sort_order description currently reads
>The route_sort_order field can be used to order the routes in a way which is ideal for presentation to customers. It must be a non-negative integer. Routes with smaller route_sort_order values should be displayed before routes with larger route_sort_order values.

and the field is listed as optional. What happens if this field is specified for some routes and left empty for others? Should the routes with empty field values go to the bottom of the list? Should this be clarified in the description?

**Comment by LeoFrachet** [comment]
Good point. I would put the empty route at the bottom, or require exhaustivity when used. @barbeau, any opinion?

**Comment by barbeau** [comment]
I think this is one of those fields that is optional, but if provided for any records it must be provided for all records.

**Comment by e-lo** [comment]
It would be useful to clarify the default value. Is it zero?
